//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Research.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division_QuestionsAnswer
    {
        public int DivisionID { get; set; }
        public int RPQ_ID { get; set; }
        public string Answer { get; set; }
        public int DQA_ID { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual RP_Question RP_Question { get; set; }
    }
}
