//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Research.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Division()
        {
            this.Division1 = new HashSet<Division>();
            this.Staff = new HashSet<Staff>();
            this.DivisionProject = new HashSet<DivisionProject>();
            this.StudentFact = new HashSet<StudentFact>();
        }
    
        public int DivisionID { get; set; }
        public string Office { get; set; }
        public string Floor { get; set; }
        public string Building { get; set; }
        public string StreetAddress { get; set; }
        public string Campus { get; set; }
        public Nullable<int> BaseDivisionID { get; set; }
        public int DT_ID { get; set; }
        public string DivisionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Division> Division1 { get; set; }
        public virtual Division Division2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionProject> DivisionProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFact> StudentFact { get; set; }
        public virtual DivisionType DivisionType { get; set; }
    }
}
